### ISSUE TITLE
Update Forecast.R to Projection.R

### ISSUE THREAD

**Issue by Bai-Li-NOAA** [nmfs-fish-tools/fishdictionary#31]
Hi @kellijohnson-NOAA, in the manuscript, projection is treated as an exemplary term in the text analysis. Do we need to update the Forecast.R file in the repo to keep consistency?

**Comment by kellijohnson-NOAA** [comment]
I think it would be best to have both terms in the dictionary because both are related to future states though in fisheries management we are most often concerned with projections. I can open a pull request with some changes if you want?

**Comment by Bai-Li-NOAA** [comment]
Having both terms in the dictionary sounds good. Thanks!

**Comment by kellijohnson-NOAA** [comment]
Tied to #20
