### ISSUE TITLE
Use json schema to validate terms in the dictionary

### ISSUE THREAD

**Issue by Bai-Li-NOAA** [nmfs-fish-tools/fishdictionary#37]
We have a json schema file [here](https://github.com/nmfs-fish-tools/fishdictionary/blob/main/inst/extdata/schema.json). It would be great if we can use the schema file to validate all [existing terms](https://github.com/nmfs-fish-tools/fishdictionary/tree/main/R) in the dictionary (.R files) or new terms in the future.

**Comment by k-doering-NOAA** [comment]
I think the idea is slightly different, but in case it is helpful, I recently setup a job to validate JSON files using a JSON schema for the FIT webpages: https://github.com/noaa-fisheries-integrated-toolbox/toolbox_web_templating/blob/main/.github/workflows/validate_json_config.yml (not sure if you have access, but I can add you if needed!)
